In [1]:
file= "https://raw.githubusercontent.com/Ambatkar/Test_mnist/main/data/Amazon_jobs_dataset%20-%20amazon_jobs_dataset.csv"

In [2]:
import pandas as pd
import csv

In [3]:
df = pd.read_csv(file)
df.head()

,S.No.,Title,location,Posting_date,DESCRIPTION,BASIC QUALIFICATIONS,PREFERRED QUALIFICATIONS
0,0,Software Development Manager,"US, WA, Seattle","March 1, 2018",You are an experienced hands-on manager with a...,· Proven track record of hiring and managing h...,· Experience building extremely high volume an...
1,1,Software Development Engineer,"IN, KA, Bangalore","March 1, 2018",Amazon is driven by being “the world’s most cu...,· Bachelor’s Degree in Computer Science or rel...,· Experience building complex software systems...
2,2,Software Development Engineer,"IN, KA, Bangalore","March 1, 2018",Amazon is driven by being “the world’s most cu...,· Bachelor’s Degree in Computer Science or rel...,· Experience building complex software systems...
3,3,Software Development Engineer - Amazon Lex,"US, WA, Seattle","March 1, 2018",Have you ever wondered what it takes to build ...,· Bachelors Degree in Computer Science or a re...,· Masters or PhD in Computer Science· Experien...
4,4,Software Development Engineer - Amazon Lex,"US, WA, Seattle","March 1, 2018",Have you ever wondered what it takes to build ...,· Bachelors Degree in Computer Science or a re...,· Masters or PhD in Computer Science· Experien...

In [4]:
filename= '../../DataSet/Amazon_jobs_dataset - amazon_jobs_dataset.csv'

In [5]:
with open(filename,encoding='utf-8') as f:
    data = csv.DictReader(f)
    data =list(data)

# HANDS ON DATA 👐

## **Job Location**

**Problem Statement :**

Find number of job openings in Bangalore,IN and in Seattle,US?

Print the Number of Job opening in Bangalore and Seattle as Integer value.

```
Output:

CountBangalore CountSeattle
```

In [6]:
# ANSWER HERE
bn = []
se=[]
opening=['Bangalore,IN', 'Seattle,US']
text= 'Bangalore'
text1='Seattle'
count=0

for i in data:
    x= i['location'].find(text)
    y= i['location'].find(text1)
    if x!= -1:
        bn.append(x)
    if y!= -1:
        se.append(x)
            
print(len(bn))
print(len(se))

66
1856

## **Job Computer Vision**


**Problem Statement :**

What are the total number of job openings related to Computer Vision ?

Note:For finding the job related to computer vision check the Job Title column.

```
Output Format

Count

```

In [7]:
# ANSWER HERE
cv= 'Computer Vision'
count=0
for i in data:
    if cv in i['Title']:
        print(i['Title'])
        count=count+1
print(count)

Software Development Engineer - Computer Vision
Software Development Manager - Computer Vision
Software Development Engineer - Computer Vision
Senior Software Development Engineer - Computer Vision
Senior Software Development Engineer - Computer Vision
Software Development Manager - Computer Vision
Computer Vision Applied Scientist
Software Development Engineer - Computer Vision
Software Development Engineer - Computer Vision
Principal Computer Vision Scientist
Software Development Engineer - Computer Vision Frameworks/Acceleration
Computer Vision and Deep Learning Research Scientist
Software Development Engineer - Computer Vision
Software Development Engineer - Computer Vision
14

In [8]:
# 14

## **Job Canada**

It is a dataset including information on amazon job opening around the world from June 2011 to March 2018. This dataset is collected using Selenium and BeautifulSoup by scraping all of the jobs for Amazon job site.
Problem Statement :

Find the number of job openings in Canada?

Print the count as the Integer Value

```
Output:

Count
```

In [9]:
# ANSWER HERE
count=0
for i in data:
    if i['location'][0:2]=='CA':
        count+=1
print(count)

156

In [10]:
# 156

## **Job Month 2018**

Problem Statement :

Find the month having most job openings in Year 2018 ?
Print the month (Month Name i.e January, February, March) and Number of job opening as Integer Value

```
Output Format :

MonthName Count

```

In [11]:
# ANSWER HERE
x,y,z=0,0,0

for i in data:
    j=int(i['Posting_date'].split(',')[1])
#     print(j)
    k=i['Posting_date'].split(' ')[0]
#     print(k)
    if j==2018:
        if k=='January':
            x+=1
        if k=='February':
            y=y+1
        if k=='March':
            z+=1

print('January',max([x,y,z]))

January 907

In [12]:
# January   907

## **Job Degree**

Problem Statement :
Find the number of job openings are present if applicant have Bachelor degree?
Print the count as Integer value

**Note : Here we will use the BASIC QUALIFICATIONS feature to find out whether bachelor degree for Job is required or not. Keywords that can be used are 'Bachelor', 'BS' and 'BA'.**

```
Output:

Count
```

In [35]:
# ANSWER HERE
listt= ['Bachelor','BS','BA']
j=set()
for i in range(len(data)):
    d=data[i]['BASIC QUALIFICATIONS']
    for k in listt:
        if k in d:
            j.add(i)
print(len(j))

2961

In [ ]:
# 2961

## **Job Java**
**Problem Statement :**

Find the country does Amazon need the most number of Java Developer?
Print the Country(Country Shortcut as given in Dataset) and number of job opening as integer value

```
Country NumberofJobs

For example : US 40
```

In [64]:
list1=[]
kword=['Java','java']
for j in range(len(data)):
    city = data[j]['location'].split(',')[0]
    if city not in list1:
        list1.append(city)
print(list1)

['US', 'IN', 'RO', 'CA', 'DE', 'PL', 'AE', 'ES', 'IT', 'IL', 'UK', 'ZA', 'SG', 'AU', 'IE', 'FR', 'BR', 'CN', 'MX', 'NL', 'JO', 'TW', 'LU', 'JP', '']

In [68]:
for i in data:
    da=i['DESCRIPTION']
    for l in kword:

Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java
Java

In [ ]:
# US   2009